<?php

return [
    "ANDAMAN AND NICOBAR ISLANDS" =>  [
        "NICOBARS",
        "NORTH AND MIDDLE ANDAMAN",
        "SOUTH ANDAMANS"
    ],
    "ANDHRA PRADESH" =>  [
        "ANANTAPUR",
        "CHITTOOR",
        "EAST GODAVARI",
        "GUNTUR",
        "KRISHNA",
        "KURNOOL",
        "PRAKASAM",
        "SPSR NELLORE",
        "SRIKAKULAM",
        "VISAKHAPATANAM",
        "VIZIANAGARAM",
        "WEST GODAVARI",
        "Y.S.R."
    ],
    "ARUNACHAL PRADESH" =>  [
        "ANJAW",
        "CHANGLANG",
        "DIBANG VALLEY",
        "EAST KAMENG",
        "EAST SIANG",
        "KRA DAADI",
        "KURUNG KUMEY",
        "LOHIT",
        "LONGDING",
        "LOWER DIBANG VALLEY",
        "LOWER SUBANSIRI",
        "NAMSAI",
        "PAPUM PARE",
        "SIANG",
        "TAWANG",
        "TIRAP",
        "UPPER SIANG",
        "UPPER SUBANSIRI",
        "WEST KAMENG",
        "WEST SIANG"
    ],
    "ASSAM" =>  [
        "BAKSA",
        "BARPETA",
        "BONGAIGAON",
        "CACHAR",
        "CHIRANG",
        "DARRANG",
        "DHEMAJI",
        "DHUBRI",
        "DIBRUGARH",
        "DIMA HASAO",
        "GOALPARA",
        "GOLAGHAT",
        "HAILAKANDI",
        "JORHAT",
        "KAMRUP",
        "KAMRUP METRO",
        "KARBI ANGLONG",
        "KARIMGANJ",
        "KOKRAJHAR",
        "LAKHIMPUR",
        "MARIGAON",
        "NAGAON",
        "NALBARI",
        "SIVASAGAR",
        "SONITPUR",
        "TINSUKIA",
        "UDALGURI"
    ],
    "BIHAR" =>  [
        "ARARIA",
        "ARWAL",
        "AURANGABAD",
        "BANKA",
        "BEGUSARAI",
        "BHAGALPUR",
        "BHOJPUR",
        "BUXAR",
        "DARBHANGA",
        "GAYA",
        "GOPALGANJ",
        "JAMUI",
        "JEHANABAD",
        "KAIMUR (BHABUA)",
        "KATIHAR",
        "KHAGARIA",
        "KISHANGANJ",
        "LAKHISARAI",
        "MADHEPURA",
        "MADHUBANI",
        "MUNGER",
        "MUZAFFARPUR",
        "NALANDA",
        "NAWADA",
        "PASHCHIM CHAMPARAN",
        "PATNA",
        "PURBI CHAMPARAN",
        "PURNIA",
        "ROHTAS",
        "SAHARSA",
        "SAMASTIPUR",
        "SARAN",
        "SHEIKHPURA",
        "SHEOHAR",
        "SITAMARHI",
        "SIWAN",
        "SUPAUL",
        "VAISHALI"
    ],
    "CHANDIGARH" =>  [
        "CHANDIGARH"
    ],
    "CHHATTISGARH" =>  [
        "BALOD",
        "BALODA BAZAR",
        "BALRAMPUR",
        "BASTAR",
        "BEMETARA",
        "BIJAPUR",
        "BILASPUR",
        "DANTEWADA",
        "DHAMTARI",
        "DURG",
        "GARIYABAND",
        "JANJGIR-CHAMPA",
        "JASHPUR",
        "KABIRDHAM",
        "KANKER",
        "KONDAGAON",
        "KORBA",
        "KOREA",
        "MAHASAMUND",
        "MUNGELI",
        "NARAYANPUR",
        "RAIGARH",
        "RAIPUR",
        "RAJNANDGAON",
        "SUKMA",
        "SURAJPUR",
        "SURGUJA"
    ],
    "DADRA AND NAGAR HAVELI" =>  [
        "DADRA AND NAGAR HAVELI"
    ],
    "DAMAN AND DIU" =>  [
        "DAMAN",
        "DIU"
    ],
    "DELHI" =>  [
        "CENTRAL",
        "EAST",
        "NEW DELHI",
        "NORTH",
        "NORTH EAST",
        "NORTH WEST",
        "SHAHDARA",
        "SOUTH",
        "SOUTH EAST",
        "SOUTH WEST",
        "WEST"
    ],
    "GOA" =>  [
        "NORTH GOA",
        "SOUTH GOA"
    ],
    "GUJARAT" =>  [
        "AHMADABAD",
        "AMRELI",
        "ANAND",
        "ARVALLI",
        "BANAS KANTHA",
        "BHARUCH",
        "BHAVNAGAR",
        "BOTAD",
        "CHHOTAUDEPUR",
        "DANG",
        "DEVBHUMI DWARKA",
        "DOHAD",
        "GANDHINAGAR",
        "GIR SOMNATH",
        "JAMNAGAR",
        "JUNAGADH",
        "KACHCHH",
        "KHEDA",
        "MAHESANA",
        "MAHISAGAR",
        "MORBI",
        "NARMADA",
        "NAVSARI",
        "PANCH MAHALS",
        "PATAN",
        "PORBANDAR",
        "RAJKOT",
        "SABAR KANTHA",
        "SURAT",
        "SURENDRANAGAR",
        "TAPI",
        "VADODARA",
        "VALSAD"
    ],
    "HARYANA" =>  [
        "AMBALA",
        "BHIWANI",
        "CHARKI DADRI",
        "FARIDABAD",
        "FATEHABAD",
        "GURUGRAM",
        "HISAR",
        "JHAJJAR",
        "JIND",
        "KAITHAL",
        "KARNAL",
        "KURUKSHETRA",
        "MAHENDRAGARH",
        "MEWAT",
        "PALWAL",
        "PANCHKULA",
        "PANIPAT",
        "REWARI",
        "ROHTAK",
        "SIRSA",
        "SONIPAT",
        "YAMUNANAGAR"
    ],
    "HIMACHAL PRADESH" =>  [
        "BILASPUR",
        "CHAMBA",
        "HAMIRPUR",
        "KANGRA",
        "KINNAUR",
        "KULLU",
        "LAHUL AND SPITI",
        "MANDI",
        "SHIMLA",
        "SIRMAUR",
        "SOLAN",
        "UNA"
    ],
    "JAMMU AND KASHMIR" =>  [
        "ANANTNAG",
        "BADGAM",
        "BANDIPORA",
        "BARAMULLA",
        "DODA",
        "GANDERBAL",
        "JAMMU",
        "KARGIL",
        "KATHUA",
        "KISHTWAR",
        "KULGAM",
        "KUPWARA",
        "LEH LADAKH",
        "POONCH",
        "PULWAMA",
        "RAJAURI",
        "RAMBAN",
        "REASI",
        "SAMBA",
        "SHOPIAN",
        "SRINAGAR",
        "UDHAMPUR"
    ],
    "JHARKHAND" =>  [
        "BOKARO",
        "CHATRA",
        "DEOGHAR",
        "DHANBAD",
        "DUMKA",
        "EAST SINGHBUM",
        "GARHWA",
        "GIRIDIH",
        "GODDA",
        "GUMLA",
        "HAZARIBAGH",
        "JAMTARA",
        "KHUNTI",
        "KODERMA",
        "LATEHAR",
        "LOHARDAGA",
        "PAKUR",
        "PALAMU",
        "RAMGARH",
        "RANCHI",
        "SAHEBGANJ",
        "SARAIKELA KHARSAWAN",
        "SIMDEGA",
        "WEST SINGHBHUM"
    ],
    "KARNATAKA" =>  [
        "BAGALKOT",
        "BALLARI",
        "BELAGAVI",
        "BENGALURU RURAL",
        "BENGALURU URBAN",
        "BIDAR",
        "CHAMARAJANAGAR",
        "CHIKBALLAPUR",
        "CHIKKAMAGALURU",
        "CHITRADURGA",
        "DAKSHIN KANNAD",
        "DAVANGERE",
        "DHARWAD",
        "GADAG",
        "HASSAN",
        "HAVERI",
        "KALABURAGI",
        "KODAGU",
        "KOLAR",
        "KOPPAL",
        "MANDYA",
        "MYSURU",
        "RAICHUR",
        "RAMANAGARA",
        "SHIVAMOGGA",
        "TUMAKURU",
        "UDUPI",
        "UTTAR KANNAD",
        "VIJAYAPURA",
        "YADGIR"
    ],
    "KERALA" =>  [
        "ALAPPUZHA",
        "ERNAKULAM",
        "IDUKKI",
        "KANNUR",
        "KASARAGOD",
        "KOLLAM",
        "KOTTAYAM",
        "KOZHIKODE",
        "MALAPPURAM",
        "PALAKKAD",
        "PATHANAMTHITTA",
        "THIRUVANANTHAPURAM",
        "THRISSUR",
        "WAYANAD"
    ],
    "LAKSHADWEEP" =>  [
        "LAKSHADWEEP DISTRICT"
    ],
    "MADHYA PRADESH" =>  [
        "AGAR MALWA",
        "ALIRAJPUR",
        "ANUPPUR",
        "ASHOKNAGAR",
        "BALAGHAT",
        "BARWANI",
        "BETUL",
        "BHIND",
        "BHOPAL",
        "BURHANPUR",
        "CHHATARPUR",
        "CHHINDWARA",
        "DAMOH",
        "DATIA",
        "DEWAS",
        "DHAR",
        "DINDORI",
        "EAST NIMAR",
        "GUNA",
        "GWALIOR",
        "HARDA",
        "HOSHANGABAD",
        "INDORE",
        "JABALPUR",
        "JHABUA",
        "KATNI",
        "KHARGONE",
        "MANDLA",
        "MANDSAUR",
        "MORENA",
        "NARSINGHPUR",
        "NEEMUCH",
        "PANNA",
        "RAISEN",
        "RAJGARH",
        "RATLAM",
        "REWA",
        "SAGAR",
        "SATNA",
        "SEHORE",
        "SEONI",
        "SHAHDOL",
        "SHAJAPUR",
        "SHEOPUR",
        "SHIVPURI",
        "SIDHI",
        "SINGRAULI",
        "TIKAMGARH",
        "UJJAIN",
        "UMARIA",
        "VIDISHA"
    ],
    "MAHARASHTRA" =>  [
        "AHMEDNAGAR",
        "AKOLA",
        "AMRAVATI",
        "AURANGABAD",
        "BEED",
        "BHANDARA",
        "BULDHANA",
        "CHANDRAPUR",
        "DHULE",
        "GADCHIROLI",
        "GONDIA",
        "HINGOLI",
        "JALGAON",
        "JALNA",
        "KOLHAPUR",
        "LATUR",
        "MUMBAI",
        "MUMBAI SUBURBAN",
        "NAGPUR",
        "NANDED",
        "NANDURBAR",
        "NASHIK",
        "OSMANABAD",
        "PALGHAR",
        "PARBHANI",
        "PUNE",
        "RAIGAD",
        "RATNAGIRI",
        "SANGLI",
        "SATARA",
        "SINDHUDURG",
        "SOLAPUR",
        "THANE",
        "WARDHA",
        "WASHIM",
        "YAVATMAL"
    ],
    "MANIPUR" =>  [
        "BISHNUPUR",
        "CHANDEL",
        "CHURACHANDPUR",
        "IMPHAL EAST",
        "IMPHAL WEST",
        "SENAPATI",
        "TAMENGLONG",
        "THOUBAL",
        "UKHRUL"
    ],
    "MEGHALAYA" =>  [
        "EAST GARO HILLS",
        "EAST JAINTIA HILLS",
        "EAST KHASI HILLS",
        "NORTH GARO HILLS",
        "RI BHOI",
        "SOUTH GARO HILLS",
        "SOUTH WEST GARO HILLS",
        "SOUTH WEST KHASI HILLS",
        "WEST GARO HILLS",
        "WEST JAINTIA HILLS",
        "WEST KHASI HILLS"
    ],
    "MIZORAM" =>  [
        "AIZAWL",
        "CHAMPHAI",
        "KOLASIB",
        "LAWNGTLAI",
        "LUNGLEI",
        "MAMIT",
        "SAIHA",
        "SERCHHIP"
    ],
    "NAGALAND" =>  [
        "DIMAPUR",
        "KIPHIRE",
        "KOHIMA",
        "LONGLENG",
        "MOKOKCHUNG",
        "MON",
        "PEREN",
        "PHEK",
        "TUENSANG",
        "WOKHA",
        "ZUNHEBOTO"
    ],
    "ODISHA" =>  [
        "ANUGUL",
        "BALANGIR",
        "BALESHWAR",
        "BARGARH",
        "BHADRAK",
        "BOUDH",
        "CUTTACK",
        "DEOGARH",
        "DHENKANAL",
        "GAJAPATI",
        "GANJAM",
        "JAGATSINGHAPUR",
        "JAJAPUR",
        "JHARSUGUDA",
        "KALAHANDI",
        "KANDHAMAL",
        "KENDRAPARA",
        "KENDUJHAR",
        "KHORDHA",
        "KORAPUT",
        "MALKANGIRI",
        "MAYURBHANJ",
        "NABARANGPUR",
        "NAYAGARH",
        "NUAPADA",
        "PURI",
        "RAYAGADA",
        "SAMBALPUR",
        "SONEPUR",
        "SUNDARGARH"
    ],
    "PUDUCHERRY" =>  [
        "KARAIKAL",
        "MAHE",
        "PONDICHERRY",
        "YANAM"
    ],
    "PUNJAB" =>  [
        "AMRITSAR",
        "BARNALA",
        "BATHINDA",
        "FARIDKOT",
        "FATEHGARH SAHIB",
        "FAZILKA",
        "FIROZEPUR",
        "GURDASPUR",
        "HOSHIARPUR",
        "JALANDHAR",
        "KAPURTHALA",
        "LUDHIANA",
        "MANSA",
        "MOGA",
        "NAWANSHAHR",
        "PATHANKOT",
        "PATIALA",
        "RUPNAGAR",
        "SANGRUR",
        "S.A.S NAGAR",
        "SRI MUKTSAR SAHIB",
        "TARN TARAN"
    ],
    "RAJASTHAN" =>  [
        "AJMER",
        "ALWAR",
        "BANSWARA",
        "BARAN",
        "BARMER",
        "BHARATPUR",
        "BHILWARA",
        "BIKANER",
        "BUNDI",
        "CHITTORGARH",
        "CHURU",
        "DAUSA",
        "DHOLPUR",
        "DUNGARPUR",
        "GANGANAGAR",
        "HANUMANGARH",
        "JAIPUR",
        "JAISALMER",
        "JALORE",
        "JHALAWAR",
        "JHUNJHUNU",
        "JODHPUR",
        "KARAULI",
        "KOTA",
        "NAGAUR",
        "PALI",
        "PRATAPGARH",
        "RAJSAMAND",
        "SAWAI MADHOPUR",
        "SIKAR",
        "SIROHI",
        "TONK",
        "UDAIPUR"
    ],
    "SIKKIM" =>  [
        "EAST DISTRICT",
        "NORTH DISTRICT",
        "SOUTH DISTRICT",
        "WEST DISTRICT"
    ],
    "TAMIL NADU" =>  [
        "ARIYALUR",
        "CHENNAI",
        "COIMBATORE",
        "CUDDALORE",
        "DHARMAPURI",
        "DINDIGUL",
        "ERODE",
        "KANCHIPURAM",
        "KANNIYAKUMARI",
        "KARUR",
        "KRISHNAGIRI",
        "MADURAI",
        "NAGAPATTINAM",
        "NAMAKKAL",
        "PERAMBALUR",
        "PUDUKKOTTAI",
        "RAMANATHAPURAM",
        "SALEM",
        "SIVAGANGA",
        "THANJAVUR",
        "THENI",
        "THE NILGIRIS",
        "THIRUVALLUR",
        "THIRUVARUR",
        "TIRUCHIRAPPALLI",
        "TIRUNELVELI",
        "TIRUPPUR",
        "TIRUVANNAMALAI",
        "TUTICORIN",
        "VELLORE",
        "VILLUPURAM",
        "VIRUDHUNAGAR"
    ],
    "TELANGANA" =>  [
        "ADILABAD",
        "BHADRADRI",
        "HYDERABAD",
        "JAGITIAL",
        "JANGOAN",
        "JAYASHANKAR",
        "JOGULAMBA",
        "KAMAREDDY",
        "KARIMNAGAR",
        "KHAMMAM",
        "KOMARAM BHEEM ASIFABAD",
        "MAHABUBABAD",
        "MAHBUBNAGAR",
        "MANCHERIAL",
        "MEDAK",
        "MEDCHAL",
        "NAGARKURNOOL",
        "NALGONDA",
        "NIRMAL",
        "NIZAMABAD",
        "PEDDAPALLI",
        "RAJANNA",
        "RANGAREDDI",
        "SANGAREDDY",
        "SIDDIPET",
        "SURYAPET",
        "VIKARABAD",
        "WANAPARTHY",
        "WARANGAL",
        "WARANGAL URBAN",
        "YADADRI"
    ],
    "TRIPURA" =>  [
        "DHALAI",
        "GOMATI",
        "KHOWAI",
        "NORTH TRIPURA",
        "SEPAHIJALA",
        "SOUTH TRIPURA",
        "UNAKOTI",
        "WEST TRIPURA"
    ],
    "UTTARAKHAND" =>  [
        "ALMORA",
        "BAGESHWAR",
        "CHAMOLI",
        "CHAMPAWAT",
        "DEHRADUN",
        "HARIDWAR",
        "NAINITAL",
        "PAURI GARHWAL",
        "PITHORAGARH",
        "RUDRA PRAYAG",
        "TEHRI GARHWAL",
        "UDAM SINGH NAGAR",
        "UTTAR KASHI"
    ],
    "UTTAR PRADESH" =>  [
        "AGRA",
        "ALIGARH",
        "ALLAHABAD",
        "AMBEDKAR NAGAR",
        "AMETHI",
        "AMROHA",
        "AURAIYA",
        "AZAMGARH",
        "BAGHPAT",
        "BAHRAICH",
        "BALLIA",
        "BALRAMPUR",
        "BANDA",
        "BARABANKI",
        "BAREILLY",
        "BASTI",
        "BHADOHI",
        "BIJNOR",
        "BUDAUN",
        "BULANDSHAHR",
        "CHANDAULI",
        "CHITRAKOOT",
        "DEORIA",
        "ETAH",
        "ETAWAH",
        "FAIZABAD",
        "FARRUKHABAD",
        "FATEHPUR",
        "FIROZABAD",
        "GAUTAM BUDDHA NAGAR",
        "GHAZIABAD",
        "GHAZIPUR",
        "GONDA",
        "GORAKHPUR",
        "HAMIRPUR",
        "HAPUR",
        "HARDOI",
        "HATHRAS",
        "JALAUN",
        "JAUNPUR",
        "JHANSI",
        "KANNAUJ",
        "KANPUR DEHAT",
        "KANPUR NAGAR",
        "KASGANJ",
        "KAUSHAMBI",
        "KHERI",
        "KUSHI NAGAR",
        "LALITPUR",
        "LUCKNOW",
        "MAHARAJGANJ",
        "MAHOBA",
        "MAINPURI",
        "MATHURA",
        "MAU",
        "MEERUT",
        "MIRZAPUR",
        "MORADABAD",
        "MUZAFFARNAGAR",
        "PILIBHIT",
        "PRATAPGARH",
        "RAE BARELI",
        "RAMPUR",
        "SAHARANPUR",
        "SAMBHAL",
        "SANT KABEER NAGAR",
        "SHAHJAHANPUR",
        "SHAMLI",
        "SHRAVASTI",
        "SIDDHARTH NAGAR",
        "SITAPUR",
        "SONBHADRA",
        "SULTANPUR",
        "UNNAO",
        "VARANASI"
    ],
    "WEST BENGAL" =>  [
        "24 PARAGANAS NORTH",
        "24 PARAGANAS SOUTH",
        "ALIPURDUAR",
        "BANKURA",
        "BARDHAMAN",
        "BIRBHUM",
        "COOCHBEHAR",
        "DARJEELING",
        "DINAJPUR DAKSHIN",
        "DINAJPUR UTTAR",
        "HOOGHLY",
        "HOWRAH",
        "JALPAIGURI",
        "KOLKATA",
        "MALDAH",
        "MEDINIPUR EAST",
        "MEDINIPUR WEST",
        "MURSHIDABAD",
        "NADIA",
        "PURULIA"
    ]
];